language: ruby
rvm:
  - ruby-2.4.1

services:
  - postgresql

env:
  - TEST_SUITE=controllers
  - TEST_SUITE=models

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - bin/rails test test/$TEST_SUITE/*
