# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a3571716c91c13d166dae74d776f3178f68b74e29286b5f7e0d40d30d76894db76cdf10972cb43987ee917823e7d5bfa9110ca60b8e52af25e1847bd1bdd9453

test:
  secret_key_base: 72fe3b291e4ee1fe80cc643c7146ad3d96d1b143b4f77db715638ad479faa828a005607f61c42b23c6f056f08339273cc5432b72bc20ac8ed24a345180c0f024

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
